// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqpsuWcXxDUxh6Bu9JiirnMdfqJDZv-k',
    appId: '1:656722787260:web:c9df8060578c4ba81609b9',
    messagingSenderId: '656722787260',
    projectId: 'social-media-3ac79',
    authDomain: 'social-media-3ac79.firebaseapp.com',
    storageBucket: 'social-media-3ac79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3dJ9AIlUlzmdc2DEGWlKPwh_wdNb2aQ',
    appId: '1:656722787260:android:83986397c653f02e1609b9',
    messagingSenderId: '656722787260',
    projectId: 'social-media-3ac79',
    storageBucket: 'social-media-3ac79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyiSfkcV_veU-46AyeIKcJw_jaiLYBpE',
    appId: '1:656722787260:ios:e0d6334ff6c4ade71609b9',
    messagingSenderId: '656722787260',
    projectId: 'social-media-3ac79',
    storageBucket: 'social-media-3ac79.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

}